version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: leetcode_spaced_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leetcode_spaced_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Uncomment this section to run the app in Docker for testing
  # app:
  #   build: .
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/leetcode_spaced_dev
  #     DATABASE_HOST: postgres
  #     DATABASE_PORT: 5432
  #     DATABASE_USER: postgres
  #     DATABASE_PASSWORD: postgres
  #     DATABASE_NAME: leetcode_spaced_dev
  #     SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  #     PHX_HOST: ${PHX_HOST:-localhost}
  #     PORT: 4000
  #     POOL_SIZE: 10
  #     GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  #     GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - ./uploads:/app/uploads

volumes:
  postgres_data: